environment:
  matrix:
    - RUBY_VERSION: 193
    - RUBY_VERSION: 200
    - RUBY_VERSION: 218
    - RUBY_VERSION: 224
    - RUBY_VERSION: 23

install:
  - set PATH=C:\Ruby%RUBY_VERSION%\bin;%PATH%
  - bundle install

build: off

before_test:
  - ruby -v
  - gem -v
  - bundle -v

test_script:
  - bundle exec rake test:local
